// Problems data for learn and practice
export interface Problem {
  id: number
  title: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  solved: boolean // This would be dynamic based on user progress
}

export const problemsData: Record<string, Problem[]> = {
  'conditional-statements-loops': [
    { id: 1, title: 'Write a program to swap two numbers using a temporary variable.', difficulty: 'Easy', solved: true },
    { id: 2, title: 'Write a program to check whether a number is positive or negative.', difficulty: 'Easy', solved: true },
    { id: 3, title: 'Write a program to check whether a number is even or odd.', difficulty: 'Easy', solved: true },
    { id: 4, title: 'Write a program to find largest of two numbers.', difficulty: 'Easy', solved: false },
    { id: 5, title: 'Write a program to check whether a character is vowel or consonant.', difficulty: 'Easy', solved: true },
    { id: 6, title: 'Write a program to check whether a number is divisible by 5 and 11.', difficulty: 'Easy', solved: true },
    { id: 7, title: 'Write a program to calculate grade based on marks.', difficulty: 'Medium', solved: true },
    { id: 8, title: 'Write a program to calculate electricity bill based on units consumed.', difficulty: 'Medium', solved: true },
    { id: 9, title: 'Write a program to find roots of a quadratic equation.', difficulty: 'Medium', solved: false },
    { id: 10, title: 'Write a program to create a simple calculator using switch.', difficulty: 'Medium', solved: true },
    { id: 11, title: 'Write a program to display day of the week using switch.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to display month name using switch.', difficulty: 'Medium', solved: false },
    { id: 13, title: 'Write a program to implement menu-driven program using switch.', difficulty: 'Medium', solved: false },
    { id: 14, title: 'Write a program to print numbers from 1 to N.', difficulty: 'Medium', solved: true },
    { id: 15, title: 'Write a program to print even numbers between 1 and N.', difficulty: 'Medium', solved: true },
    { id: 16, title: 'Write a program to print multiplication table of a number.', difficulty: 'Medium', solved: true },
    { id: 17, title: 'Write a program to calculate factorial of a number using for loop.', difficulty: 'Medium', solved: true },
    { id: 18, title: 'Write a program to calculate sum of first N natural numbers.', difficulty: 'Medium', solved: true },
    { id: 19, title: 'Write a program to reverse a number using while loop.', difficulty: 'Hard', solved: false },
    { id: 20, title: 'Write a program to check whether a number is palindrome.', difficulty: 'Hard', solved: true },
    { id: 21, title: 'Write a program to check whether a number is Armstrong number.', difficulty: 'Hard', solved: false },
    { id: 22, title: 'Write a program to count digits in a number.', difficulty: 'Hard', solved: true },
    { id: 23, title: 'Write a program to find sum of digits of a number.', difficulty: 'Hard', solved: true },
    { id: 24, title: 'Write a program to demonstrate do-while loop.', difficulty: 'Hard', solved: false },
    { id: 25, title: 'Write a program to display menu until user chooses exit.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to validate user input using do-while loop.', difficulty: 'Hard', solved: false },
    { id: 27, title: 'Write a program to check if a number is prime.', difficulty: 'Medium', solved: false },
    { id: 28, title: 'Write a program to generate Fibonacci series.', difficulty: 'Medium', solved: false },
    { id: 29, title: 'Write a program to find GCD of two numbers.', difficulty: 'Medium', solved: false },
    { id: 30, title: 'Write a program to convert temperature from Celsius to Fahrenheit.', difficulty: 'Easy', solved: false },
  ],
  'arrays': [
    { id: 1, title: 'Write a program to find the largest element in an array.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to find the second largest element in an array.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program to find the sum of all elements in an array.', difficulty: 'Easy', solved: false },
    { id: 4, title: 'Write a program to count even and odd numbers in an array.', difficulty: 'Easy', solved: false },
    { id: 5, title: 'Write a program to copy all elements from one array to another.', difficulty: 'Easy', solved: false },
    { id: 6, title: 'Write a program to insert an element at a specific position in an array.', difficulty: 'Medium', solved: false },
    { id: 7, title: 'Write a program to delete an element from an array at a specific position.', difficulty: 'Medium', solved: false },
    { id: 8, title: 'Write a program to reverse an array.', difficulty: 'Medium', solved: false },
    { id: 9, title: 'Write a program to search an element in an array using linear search.', difficulty: 'Easy', solved: false },
    { id: 10, title: 'Write a program to sort an array in ascending order.', difficulty: 'Medium', solved: false },
    { id: 11, title: 'Write a program to merge two sorted arrays.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to find the frequency of each element in an array.', difficulty: 'Medium', solved: false },
    { id: 13, title: 'Write a program to find duplicate elements in an array.', difficulty: 'Medium', solved: false },
    { id: 14, title: 'Write a program to remove duplicates from an array.', difficulty: 'Medium', solved: false },
    { id: 15, title: 'Write a program to find the intersection of two arrays.', difficulty: 'Medium', solved: false },
    { id: 16, title: 'Write a program to find the union of two arrays.', difficulty: 'Medium', solved: false },
    { id: 17, title: 'Write a program to rotate an array by K positions.', difficulty: 'Hard', solved: false },
    { id: 18, title: 'Write a program to find the maximum subarray sum.', difficulty: 'Hard', solved: false },
    { id: 19, title: 'Write a program to implement binary search in an array.', difficulty: 'Medium', solved: false },
    { id: 20, title: 'Write a program to find the median of an array.', difficulty: 'Medium', solved: false },
    { id: 21, title: 'Write a program to find the mode of an array.', difficulty: 'Medium', solved: false },
    { id: 22, title: 'Write a program to check if an array is sorted.', difficulty: 'Easy', solved: false },
    { id: 23, title: 'Write a program to find the kth largest element in an array.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to rearrange positive and negative numbers alternately.', difficulty: 'Hard', solved: false },
    { id: 25, title: 'Write a program to find the minimum element in a rotated sorted array.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to move all zeros to the end of an array.', difficulty: 'Easy', solved: false },
    { id: 27, title: 'Write a program to find the majority element in an array.', difficulty: 'Medium', solved: false },
    { id: 28, title: 'Write a program to find the longest consecutive sequence in an array.', difficulty: 'Hard', solved: false },
    { id: 29, title: 'Write a program to implement array rotation using reversal algorithm.', difficulty: 'Medium', solved: false },
    { id: 30, title: 'Write a program to find the equilibrium index of an array.', difficulty: 'Medium', solved: false },
  ],
  'string': [
    { id: 1, title: 'Write a program to find the length of a string.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to copy one string to another.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program to concatenate two strings.', difficulty: 'Easy', solved: false },
    { id: 4, title: 'Write a program to compare two strings.', difficulty: 'Easy', solved: false },
    { id: 5, title: 'Write a program to reverse a string.', difficulty: 'Easy', solved: false },
    { id: 6, title: 'Write a program to check if a string is palindrome.', difficulty: 'Easy', solved: false },
    { id: 7, title: 'Write a program to count vowels and consonants in a string.', difficulty: 'Easy', solved: false },
    { id: 8, title: 'Write a program to find the frequency of characters in a string.', difficulty: 'Medium', solved: false },
    { id: 9, title: 'Write a program to remove all whitespaces from a string.', difficulty: 'Easy', solved: false },
    { id: 10, title: 'Write a program to toggle case of each character in a string.', difficulty: 'Medium', solved: false },
    { id: 11, title: 'Write a program to find the first non-repeating character in a string.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to check if two strings are anagrams.', difficulty: 'Medium', solved: false },
    { id: 13, title: 'Write a program to find the longest common prefix in an array of strings.', difficulty: 'Medium', solved: false },
    { id: 14, title: 'Write a program to implement string compression.', difficulty: 'Medium', solved: false },
    { id: 15, title: 'Write a program to check if a string contains only digits.', difficulty: 'Easy', solved: false },
    { id: 16, title: 'Write a program to convert string to uppercase.', difficulty: 'Easy', solved: false },
    { id: 17, title: 'Write a program to convert string to lowercase.', difficulty: 'Easy', solved: false },
    { id: 18, title: 'Write a program to find the substring in a string.', difficulty: 'Medium', solved: false },
    { id: 19, title: 'Write a program to replace a substring in a string.', difficulty: 'Medium', solved: false },
    { id: 20, title: 'Write a program to count the number of words in a string.', difficulty: 'Easy', solved: false },
    { id: 21, title: 'Write a program to remove duplicate characters from a string.', difficulty: 'Medium', solved: false },
    { id: 22, title: 'Write a program to check if a string is a valid email address.', difficulty: 'Medium', solved: false },
    { id: 23, title: 'Write a program to implement string permutation.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to find all permutations of a string.', difficulty: 'Hard', solved: false },
    { id: 25, title: 'Write a program to implement Rabin-Karp algorithm for string matching.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to implement KMP algorithm for string matching.', difficulty: 'Hard', solved: false },
    { id: 27, title: 'Write a program to find the longest palindromic substring.', difficulty: 'Hard', solved: false },
    { id: 28, title: 'Write a program to implement string to integer conversion (atoi).', difficulty: 'Medium', solved: false },
    { id: 29, title: 'Write a program to implement integer to string conversion (itoa).', difficulty: 'Medium', solved: false },
    { id: 30, title: 'Write a program to find the edit distance between two strings.', difficulty: 'Hard', solved: false },
  ],
  // Add more topics as needed
  'recursion': [
    { id: 1, title: 'Write a program to calculate factorial using recursion.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to generate Fibonacci series using recursion.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program to calculate power using recursion.', difficulty: 'Easy', solved: false },
    { id: 4, title: 'Write a program to reverse a string using recursion.', difficulty: 'Medium', solved: false },
    { id: 5, title: 'Write a program to check palindrome using recursion.', difficulty: 'Medium', solved: false },
    { id: 6, title: 'Write a program to find GCD using recursion.', difficulty: 'Easy', solved: false },
    { id: 7, title: 'Write a program to solve Tower of Hanoi.', difficulty: 'Hard', solved: false },
    { id: 8, title: 'Write a program to print all permutations of a string.', difficulty: 'Hard', solved: false },
    { id: 9, title: 'Write a program to implement binary search using recursion.', difficulty: 'Medium', solved: false },
    { id: 10, title: 'Write a program to calculate sum of digits using recursion.', difficulty: 'Easy', solved: false },
    { id: 11, title: 'Write a program to find maximum element in array using recursion.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to implement merge sort.', difficulty: 'Hard', solved: false },
    { id: 13, title: 'Write a program to implement quick sort.', difficulty: 'Hard', solved: false },
    { id: 14, title: 'Write a program to solve N-Queens problem.', difficulty: 'Hard', solved: false },
    { id: 15, title: 'Write a program to find all subsets of a set.', difficulty: 'Hard', solved: false },
    { id: 16, title: 'Write a program to implement flood fill algorithm.', difficulty: 'Medium', solved: false },
    { id: 17, title: 'Write a program to calculate binomial coefficient.', difficulty: 'Medium', solved: false },
    { id: 18, title: 'Write a program to implement backtracking for sudoku.', difficulty: 'Hard', solved: false },
    { id: 19, title: 'Write a program to find all paths in a maze.', difficulty: 'Hard', solved: false },
    { id: 20, title: 'Write a program to implement recursive tree traversal.', difficulty: 'Medium', solved: false },
    { id: 21, title: 'Write a program to calculate determinant of matrix using recursion.', difficulty: 'Hard', solved: false },
    { id: 22, title: 'Write a program to implement recursive knapsack.', difficulty: 'Hard', solved: false },
    { id: 23, title: 'Write a program to find longest common subsequence.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to implement recursive graph traversal.', difficulty: 'Medium', solved: false },
    { id: 25, title: 'Write a program to solve rat in maze problem.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to implement recursive exponentiation.', difficulty: 'Medium', solved: false },
    { id: 27, title: 'Write a program to find all combinations of size k.', difficulty: 'Hard', solved: false },
    { id: 28, title: 'Write a program to implement recursive string matching.', difficulty: 'Medium', solved: false },
    { id: 29, title: 'Write a program to solve word break problem.', difficulty: 'Hard', solved: false },
    { id: 30, title: 'Write a program to implement recursive palindrome partitioning.', difficulty: 'Hard', solved: false },
  ],
  'searching': [
    { id: 1, title: 'Write a program to implement linear search.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to implement binary search.', difficulty: 'Medium', solved: false },
    { id: 3, title: 'Write a program to implement ternary search.', difficulty: 'Medium', solved: false },
    { id: 4, title: 'Write a program to implement jump search.', difficulty: 'Medium', solved: false },
    { id: 5, title: 'Write a program to implement interpolation search.', difficulty: 'Hard', solved: false },
    { id: 6, title: 'Write a program to implement exponential search.', difficulty: 'Medium', solved: false },
    { id: 7, title: 'Write a program to find first occurrence in sorted array.', difficulty: 'Medium', solved: false },
    { id: 8, title: 'Write a program to find last occurrence in sorted array.', difficulty: 'Medium', solved: false },
    { id: 9, title: 'Write a program to count occurrences in sorted array.', difficulty: 'Medium', solved: false },
    { id: 10, title: 'Write a program to find peak element in array.', difficulty: 'Medium', solved: false },
    { id: 11, title: 'Write a program to search in rotated sorted array.', difficulty: 'Hard', solved: false },
    { id: 12, title: 'Write a program to implement binary search on answer.', difficulty: 'Hard', solved: false },
    { id: 13, title: 'Write a program to find square root using binary search.', difficulty: 'Medium', solved: false },
    { id: 14, title: 'Write a program to implement meta binary search.', difficulty: 'Hard', solved: false },
    { id: 15, title: 'Write a program to search in 2D matrix.', difficulty: 'Medium', solved: false },
    { id: 16, title: 'Write a program to implement Fibonacci search.', difficulty: 'Hard', solved: false },
    { id: 17, title: 'Write a program to find minimum in rotated array.', difficulty: 'Medium', solved: false },
    { id: 18, title: 'Write a program to implement order-agnostic binary search.', difficulty: 'Easy', solved: false },
    { id: 19, title: 'Write a program to find ceiling of number in sorted array.', difficulty: 'Medium', solved: false },
    { id: 20, title: 'Write a program to find floor of number in sorted array.', difficulty: 'Medium', solved: false },
    { id: 21, title: 'Write a program to implement unbounded binary search.', difficulty: 'Hard', solved: false },
    { id: 22, title: 'Write a program to search in infinite sorted array.', difficulty: 'Medium', solved: false },
    { id: 23, title: 'Write a program to find k closest elements.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to implement binary search on floating point.', difficulty: 'Medium', solved: false },
    { id: 25, title: 'Write a program to find median of two sorted arrays.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to implement recursive binary search.', difficulty: 'Easy', solved: false },
    { id: 27, title: 'Write a program to find element in nearly sorted array.', difficulty: 'Medium', solved: false },
    { id: 28, title: 'Write a program to implement sentinel linear search.', difficulty: 'Easy', solved: false },
    { id: 29, title: 'Write a program to search in row-wise and column-wise sorted matrix.', difficulty: 'Medium', solved: false },
    { id: 30, title: 'Write a program to find the missing number in array.', difficulty: 'Easy', solved: false },
  ],
  'sorting': [
    { id: 1, title: 'Write a program to implement bubble sort.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to implement selection sort.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program to implement insertion sort.', difficulty: 'Easy', solved: false },
    { id: 4, title: 'Write a program to implement merge sort.', difficulty: 'Medium', solved: false },
    { id: 5, title: 'Write a program to implement quick sort.', difficulty: 'Medium', solved: false },
    { id: 6, title: 'Write a program to implement heap sort.', difficulty: 'Hard', solved: false },
    { id: 7, title: 'Write a program to implement counting sort.', difficulty: 'Medium', solved: false },
    { id: 8, title: 'Write a program to implement radix sort.', difficulty: 'Hard', solved: false },
    { id: 9, title: 'Write a program to implement bucket sort.', difficulty: 'Medium', solved: false },
    { id: 10, title: 'Write a program to implement shell sort.', difficulty: 'Medium', solved: false },
    { id: 11, title: 'Write a program to implement comb sort.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to implement pancake sorting.', difficulty: 'Hard', solved: false },
    { id: 13, title: 'Write a program to implement cycle sort.', difficulty: 'Medium', solved: false },
    { id: 14, title: 'Write a program to implement timsort.', difficulty: 'Hard', solved: false },
    { id: 15, title: 'Write a program to implement introsort.', difficulty: 'Hard', solved: false },
    { id: 16, title: 'Write a program to sort array of 0s, 1s and 2s.', difficulty: 'Easy', solved: false },
    { id: 17, title: 'Write a program to sort array in wave form.', difficulty: 'Medium', solved: false },
    { id: 18, title: 'Write a program to sort array with two types of elements.', difficulty: 'Easy', solved: false },
    { id: 19, title: 'Write a program to sort array by frequency.', difficulty: 'Medium', solved: false },
    { id: 20, title: 'Write a program to sort array containing 0s and 1s.', difficulty: 'Easy', solved: false },
    { id: 21, title: 'Write a program to sort strings by length.', difficulty: 'Easy', solved: false },
    { id: 22, title: 'Write a program to implement stable sort.', difficulty: 'Medium', solved: false },
    { id: 23, title: 'Write a program to sort array using recursion.', difficulty: 'Medium', solved: false },
    { id: 24, title: 'Write a program to implement external sort.', difficulty: 'Hard', solved: false },
    { id: 25, title: 'Write a program to sort linked list.', difficulty: 'Medium', solved: false },
    { id: 26, title: 'Write a program to implement topological sort.', difficulty: 'Hard', solved: false },
    { id: 27, title: 'Write a program to sort array of dates.', difficulty: 'Medium', solved: false },
    { id: 28, title: 'Write a program to implement Dutch National Flag algorithm.', difficulty: 'Medium', solved: false },
    { id: 29, title: 'Write a program to sort array in alternating order.', difficulty: 'Medium', solved: false },
    { id: 30, title: 'Write a program to implement k-way merge sort.', difficulty: 'Hard', solved: false },
  ],
  'linked-list': [
    { id: 1, title: 'Write a program to create a linked list.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to traverse a linked list.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program to insert node at beginning.', difficulty: 'Easy', solved: false },
    { id: 4, title: 'Write a program to insert node at end.', difficulty: 'Easy', solved: false },
    { id: 5, title: 'Write a program to insert node at specific position.', difficulty: 'Medium', solved: false },
    { id: 6, title: 'Write a program to delete node from beginning.', difficulty: 'Easy', solved: false },
    { id: 7, title: 'Write a program to delete node from end.', difficulty: 'Easy', solved: false },
    { id: 8, title: 'Write a program to delete node at specific position.', difficulty: 'Medium', solved: false },
    { id: 9, title: 'Write a program to search element in linked list.', difficulty: 'Easy', solved: false },
    { id: 10, title: 'Write a program to find length of linked list.', difficulty: 'Easy', solved: false },
    { id: 11, title: 'Write a program to reverse a linked list.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to detect loop in linked list.', difficulty: 'Medium', solved: false },
    { id: 13, title: 'Write a program to remove loop from linked list.', difficulty: 'Hard', solved: false },
    { id: 14, title: 'Write a program to find middle element.', difficulty: 'Easy', solved: false },
    { id: 15, title: 'Write a program to find nth node from end.', difficulty: 'Medium', solved: false },
    { id: 16, title: 'Write a program to merge two sorted linked lists.', difficulty: 'Medium', solved: false },
    { id: 17, title: 'Write a program to remove duplicates from sorted list.', difficulty: 'Easy', solved: false },
    { id: 18, title: 'Write a program to implement doubly linked list.', difficulty: 'Medium', solved: false },
    { id: 19, title: 'Write a program to implement circular linked list.', difficulty: 'Medium', solved: false },
    { id: 20, title: 'Write a program to implement stack using linked list.', difficulty: 'Easy', solved: false },
    { id: 21, title: 'Write a program to implement queue using linked list.', difficulty: 'Easy', solved: false },
    { id: 22, title: 'Write a program to add two numbers represented by linked lists.', difficulty: 'Hard', solved: false },
    { id: 23, title: 'Write a program to rotate linked list by k positions.', difficulty: 'Medium', solved: false },
    { id: 24, title: 'Write a program to find intersection point of two linked lists.', difficulty: 'Hard', solved: false },
    { id: 25, title: 'Write a program to check if linked list is palindrome.', difficulty: 'Medium', solved: false },
    { id: 26, title: 'Write a program to implement LRU cache using linked list.', difficulty: 'Hard', solved: false },
    { id: 27, title: 'Write a program to flatten a multilevel linked list.', difficulty: 'Hard', solved: false },
    { id: 28, title: 'Write a program to sort linked list using merge sort.', difficulty: 'Hard', solved: false },
    { id: 29, title: 'Write a program to implement skip list.', difficulty: 'Hard', solved: false },
    { id: 30, title: 'Write a program to clone linked list with random pointers.', difficulty: 'Hard', solved: false },
  ],
  'stack': [
    { id: 1, title: 'Write a program to implement stack using array.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to implement stack using linked list.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program to check balanced parentheses.', difficulty: 'Easy', solved: false },
    { id: 4, title: 'Write a program to evaluate postfix expression.', difficulty: 'Medium', solved: false },
    { id: 5, title: 'Write a program to convert infix to postfix.', difficulty: 'Medium', solved: false },
    { id: 6, title: 'Write a program to find next greater element.', difficulty: 'Medium', solved: false },
    { id: 7, title: 'Write a program to find previous greater element.', difficulty: 'Medium', solved: false },
    { id: 8, title: 'Write a program to find next smaller element.', difficulty: 'Medium', solved: false },
    { id: 9, title: 'Write a program to implement min stack.', difficulty: 'Medium', solved: false },
    { id: 10, title: 'Write a program to implement stack with max API.', difficulty: 'Medium', solved: false },
    { id: 11, title: 'Write a program to sort stack using recursion.', difficulty: 'Hard', solved: false },
    { id: 12, title: 'Write a program to reverse stack using recursion.', difficulty: 'Medium', solved: false },
    { id: 13, title: 'Write a program to implement two stacks in one array.', difficulty: 'Medium', solved: false },
    { id: 14, title: 'Write a program to find largest rectangle in histogram.', difficulty: 'Hard', solved: false },
    { id: 15, title: 'Write a program to find maximum area of island.', difficulty: 'Medium', solved: false },
    { id: 16, title: 'Write a program to implement stock span problem.', difficulty: 'Medium', solved: false },
    { id: 17, title: 'Write a program to find celebrity problem.', difficulty: 'Hard', solved: false },
    { id: 18, title: 'Write a program to implement iterative inorder traversal.', difficulty: 'Medium', solved: false },
    { id: 19, title: 'Write a program to implement iterative preorder traversal.', difficulty: 'Medium', solved: false },
    { id: 20, title: 'Write a program to implement iterative postorder traversal.', difficulty: 'Medium', solved: false },
    { id: 21, title: 'Write a program to find redundant brackets.', difficulty: 'Easy', solved: false },
    { id: 22, title: 'Write a program to implement stack permutations.', difficulty: 'Hard', solved: false },
    { id: 23, title: 'Write a program to find minimum cost to make string valid.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to implement asteroid collision.', difficulty: 'Medium', solved: false },
    { id: 25, title: 'Write a program to find maximum frequency stack.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to implement LRU cache.', difficulty: 'Hard', solved: false },
    { id: 27, title: 'Write a program to find the longest valid parentheses.', difficulty: 'Hard', solved: false },
    { id: 28, title: 'Write a program to implement stack using queues.', difficulty: 'Medium', solved: false },
    { id: 29, title: 'Write a program to find expression evaluation.', difficulty: 'Hard', solved: false },
    { id: 30, title: 'Write a program to implement monotonic stack.', difficulty: 'Medium', solved: false },
  ],
  'queue': [
    { id: 1, title: 'Write a program to implement queue using array.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to implement queue using linked list.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program to implement circular queue.', difficulty: 'Medium', solved: false },
    { id: 4, title: 'Write a program to implement deque.', difficulty: 'Medium', solved: false },
    { id: 5, title: 'Write a program to implement priority queue.', difficulty: 'Medium', solved: false },
    { id: 6, title: 'Write a program to implement queue using two stacks.', difficulty: 'Medium', solved: false },
    { id: 7, title: 'Write a program to implement stack using two queues.', difficulty: 'Medium', solved: false },
    { id: 8, title: 'Write a program to find first non-repeating character.', difficulty: 'Medium', solved: false },
    { id: 9, title: 'Write a program to implement sliding window maximum.', difficulty: 'Hard', solved: false },
    { id: 10, title: 'Write a program to implement level order traversal.', difficulty: 'Easy', solved: false },
    { id: 11, title: 'Write a program to implement BFS traversal.', difficulty: 'Easy', solved: false },
    { id: 12, title: 'Write a program to find rotten oranges.', difficulty: 'Medium', solved: false },
    { id: 13, title: 'Write a program to find shortest path in binary maze.', difficulty: 'Medium', solved: false },
    { id: 14, title: 'Write a program to implement job sequencing.', difficulty: 'Hard', solved: false },
    { id: 15, title: 'Write a program to find maximum in all subarrays.', difficulty: 'Hard', solved: false },
    { id: 16, title: 'Write a program to implement circular tour.', difficulty: 'Hard', solved: false },
    { id: 17, title: 'Write a program to find minimum time required.', difficulty: 'Hard', solved: false },
    { id: 18, title: 'Write a program to implement k queues in one array.', difficulty: 'Hard', solved: false },
    { id: 19, title: 'Write a program to implement queue using stack.', difficulty: 'Medium', solved: false },
    { id: 20, title: 'Write a program to find first negative in every window.', difficulty: 'Medium', solved: false },
    { id: 21, title: 'Write a program to implement sum of minimum and maximum.', difficulty: 'Hard', solved: false },
    { id: 22, title: 'Write a program to find maximum of all subarrays of size k.', difficulty: 'Medium', solved: false },
    { id: 23, title: 'Write a program to implement page replacement algorithms.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to find minimum cost to connect ropes.', difficulty: 'Medium', solved: false },
    { id: 25, title: 'Write a program to implement task scheduler.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to find time needed to buy tickets.', difficulty: 'Easy', solved: false },
    { id: 27, title: 'Write a program to implement number of recent calls.', difficulty: 'Easy', solved: false },
    { id: 28, title: 'Write a program to find shortest path in undirected graph.', difficulty: 'Medium', solved: false },
    { id: 29, title: 'Write a program to implement zigzag level order traversal.', difficulty: 'Medium', solved: false },
    { id: 30, title: 'Write a program to find all nodes at distance k.', difficulty: 'Hard', solved: false },
  ],
  'hashing': [
    { id: 1, title: 'Write a program to implement hash table.', difficulty: 'Medium', solved: false },
    { id: 2, title: 'Write a program to handle collisions using chaining.', difficulty: 'Medium', solved: false },
    { id: 3, title: 'Write a program to handle collisions using open addressing.', difficulty: 'Hard', solved: false },
    { id: 4, title: 'Write a program to find first repeating element.', difficulty: 'Easy', solved: false },
    { id: 5, title: 'Write a program to find first non-repeating element.', difficulty: 'Easy', solved: false },
    { id: 6, title: 'Write a program to find union of two arrays.', difficulty: 'Easy', solved: false },
    { id: 7, title: 'Write a program to find intersection of two arrays.', difficulty: 'Easy', solved: false },
    { id: 8, title: 'Write a program to find pair with given sum.', difficulty: 'Easy', solved: false },
    { id: 9, title: 'Write a program to find subarray with zero sum.', difficulty: 'Medium', solved: false },
    { id: 10, title: 'Write a program to find longest subarray with sum k.', difficulty: 'Medium', solved: false },
    { id: 11, title: 'Write a program to find longest consecutive subsequence.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to find largest subarray with equal 0s and 1s.', difficulty: 'Medium', solved: false },
    { id: 13, title: 'Write a program to find count of distinct elements.', difficulty: 'Easy', solved: false },
    { id: 14, title: 'Write a program to find frequency of each element.', difficulty: 'Easy', solved: false },
    { id: 15, title: 'Write a program to find elements that appear more than n/k times.', difficulty: 'Medium', solved: false },
    { id: 16, title: 'Write a program to implement LRU cache.', difficulty: 'Hard', solved: false },
    { id: 17, title: 'Write a program to find minimum indexed character.', difficulty: 'Easy', solved: false },
    { id: 18, title: 'Write a program to find winner of election.', difficulty: 'Easy', solved: false },
    { id: 19, title: 'Write a program to find symmetric pairs.', difficulty: 'Easy', solved: false },
    { id: 20, title: 'Write a program to find relative sorting.', difficulty: 'Medium', solved: false },
    { id: 21, title: 'Write a program to find array pair sum divisibility.', difficulty: 'Medium', solved: false },
    { id: 22, title: 'Write a program to find smallest window containing all characters.', difficulty: 'Hard', solved: false },
    { id: 23, title: 'Write a program to find anagrams together.', difficulty: 'Medium', solved: false },
    { id: 24, title: 'Write a program to find longest substring without repeating characters.', difficulty: 'Medium', solved: false },
    { id: 25, title: 'Write a program to implement phone directory.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to find four sum.', difficulty: 'Medium', solved: false },
    { id: 27, title: 'Write a program to find group anagrams.', difficulty: 'Medium', solved: false },
    { id: 28, title: 'Write a program to implement consistent hashing.', difficulty: 'Hard', solved: false },
    { id: 29, title: 'Write a program to find top k frequent elements.', difficulty: 'Medium', solved: false },
    { id: 30, title: 'Write a program to implement bloom filter.', difficulty: 'Hard', solved: false },
  ],
  'trees': [
    { id: 1, title: 'Write a program to create binary tree.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program for inorder traversal.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program for preorder traversal.', difficulty: 'Easy', solved: false },
    { id: 4, title: 'Write a program for postorder traversal.', difficulty: 'Easy', solved: false },
    { id: 5, title: 'Write a program for level order traversal.', difficulty: 'Easy', solved: false },
    { id: 6, title: 'Write a program to find height of binary tree.', difficulty: 'Easy', solved: false },
    { id: 7, title: 'Write a program to find diameter of binary tree.', difficulty: 'Medium', solved: false },
    { id: 8, title: 'Write a program to check if tree is balanced.', difficulty: 'Easy', solved: false },
    { id: 9, title: 'Write a program to find lowest common ancestor.', difficulty: 'Medium', solved: false },
    { id: 10, title: 'Write a program to check if two trees are identical.', difficulty: 'Easy', solved: false },
    { id: 11, title: 'Write a program to find maximum path sum.', difficulty: 'Hard', solved: false },
    { id: 12, title: 'Write a program to convert tree to its mirror.', difficulty: 'Easy', solved: false },
    { id: 13, title: 'Write a program to check if tree is symmetric.', difficulty: 'Easy', solved: false },
    { id: 14, title: 'Write a program to print root to leaf paths.', difficulty: 'Medium', solved: false },
    { id: 15, title: 'Write a program to find sum of all nodes.', difficulty: 'Easy', solved: false },
    { id: 16, title: 'Write a program to find maximum element.', difficulty: 'Easy', solved: false },
    { id: 17, title: 'Write a program to find minimum element.', difficulty: 'Easy', solved: false },
    { id: 18, title: 'Write a program to count leaf nodes.', difficulty: 'Easy', solved: false },
    { id: 19, title: 'Write a program to count internal nodes.', difficulty: 'Easy', solved: false },
    { id: 20, title: 'Write a program to find level with maximum sum.', difficulty: 'Medium', solved: false },
    { id: 21, title: 'Write a program to find deepest left leaf.', difficulty: 'Medium', solved: false },
    { id: 22, title: 'Write a program to construct tree from inorder and preorder.', difficulty: 'Medium', solved: false },
    { id: 23, title: 'Write a program to construct tree from inorder and postorder.', difficulty: 'Medium', solved: false },
    { id: 24, title: 'Write a program to find boundary traversal.', difficulty: 'Medium', solved: false },
    { id: 25, title: 'Write a program to find vertical sum.', difficulty: 'Medium', solved: false },
    { id: 26, title: 'Write a program to find top view of binary tree.', difficulty: 'Medium', solved: false },
    { id: 27, title: 'Write a program to find bottom view of binary tree.', difficulty: 'Medium', solved: false },
    { id: 28, title: 'Write a program to find right view of binary tree.', difficulty: 'Easy', solved: false },
    { id: 29, title: 'Write a program to find left view of binary tree.', difficulty: 'Easy', solved: false },
    { id: 30, title: 'Write a program to serialize and deserialize binary tree.', difficulty: 'Hard', solved: false },
  ],
  'heap': [
    { id: 1, title: 'Write a program to implement max heap.', difficulty: 'Medium', solved: false },
    { id: 2, title: 'Write a program to implement min heap.', difficulty: 'Medium', solved: false },
    { id: 3, title: 'Write a program to implement heap sort.', difficulty: 'Hard', solved: false },
    { id: 4, title: 'Write a program to find k largest elements.', difficulty: 'Medium', solved: false },
    { id: 5, title: 'Write a program to find k smallest elements.', difficulty: 'Medium', solved: false },
    { id: 6, title: 'Write a program to implement priority queue.', difficulty: 'Medium', solved: false },
    { id: 7, title: 'Write a program to merge k sorted arrays.', difficulty: 'Hard', solved: false },
    { id: 8, title: 'Write a program to find median in stream.', difficulty: 'Hard', solved: false },
    { id: 9, title: 'Write a program to implement running median.', difficulty: 'Hard', solved: false },
    { id: 10, title: 'Write a program to find kth largest element.', difficulty: 'Medium', solved: false },
    { id: 11, title: 'Write a program to find kth smallest element.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to implement huffman coding.', difficulty: 'Hard', solved: false },
    { id: 13, title: 'Write a program to find minimum cost to connect ropes.', difficulty: 'Medium', solved: false },
    { id: 14, title: 'Write a program to implement dijkstra algorithm.', difficulty: 'Hard', solved: false },
    { id: 15, title: 'Write a program to implement prims algorithm.', difficulty: 'Hard', solved: false },
    { id: 16, title: 'Write a program to find top k frequent elements.', difficulty: 'Medium', solved: false },
    { id: 17, title: 'Write a program to implement sliding window maximum.', difficulty: 'Hard', solved: false },
    { id: 18, title: 'Write a program to find maximum sum combination.', difficulty: 'Hard', solved: false },
    { id: 19, title: 'Write a program to implement binary heap.', difficulty: 'Medium', solved: false },
    { id: 20, title: 'Write a program to implement fibonacci heap.', difficulty: 'Hard', solved: false },
    { id: 21, title: 'Write a program to find smallest range in k lists.', difficulty: 'Hard', solved: false },
    { id: 22, title: 'Write a program to implement job scheduling.', difficulty: 'Hard', solved: false },
    { id: 23, title: 'Write a program to find maximum profit in job scheduling.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to implement binomial heap.', difficulty: 'Hard', solved: false },
    { id: 25, title: 'Write a program to find k closest points to origin.', difficulty: 'Medium', solved: false },
    { id: 26, title: 'Write a program to implement heap using array.', difficulty: 'Easy', solved: false },
    { id: 27, title: 'Write a program to implement heap using linked list.', difficulty: 'Medium', solved: false },
    { id: 28, title: 'Write a program to find skyline problem.', difficulty: 'Hard', solved: false },
    { id: 29, title: 'Write a program to implement merge k sorted lists.', difficulty: 'Hard', solved:  false },
    { id: 30, title: 'Write a program to find minimum time to burn tree.', difficulty: 'Hard', solved: false },
  ],
  'graphs': [
    { id: 1, title: 'Write a program to implement adjacency list.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to implement adjacency matrix.', difficulty: 'Easy', solved: false },
    { id: 3, title: 'Write a program to implement BFS traversal.', difficulty: 'Easy', solved: false },
    { id: 4, title: 'Write a program to implement DFS traversal.', difficulty: 'Easy', solved: false },
    { id: 5, title: 'Write a program to detect cycle in undirected graph.', difficulty: 'Medium', solved: false },
    { id: 6, title: 'Write a program to detect cycle in directed graph.', difficulty: 'Medium', solved: false },
    { id: 7, title: 'Write a program to implement topological sort.', difficulty: 'Medium', solved: false },
    { id: 8, title: 'Write a program to find shortest path using BFS.', difficulty: 'Easy', solved: false },
    { id: 9, title: 'Write a program to implement dijkstra algorithm.', difficulty: 'Hard', solved: false },
    { id: 10, title: 'Write a program to implement bellman ford algorithm.', difficulty: 'Hard', solved: false },
    { id: 11, title: 'Write a program to implement floyd warshall algorithm.', difficulty: 'Hard', solved: false },
    { id: 12, title: 'Write a program to find minimum spanning tree using kruskal.', difficulty: 'Hard', solved: false },
    { id: 13, title: 'Write a program to find minimum spanning tree using prim.', difficulty: 'Hard', solved: false },
    { id: 14, title: 'Write a program to find bridges in graph.', difficulty: 'Hard', solved: false },
    { id: 15, title: 'Write a program to find articulation points.', difficulty: 'Hard', solved: false },
    { id: 16, title: 'Write a program to implement union find.', difficulty: 'Medium', solved: false },
    { id: 17, title: 'Write a program to find strongly connected components.', difficulty: 'Hard', solved: false },
    { id: 18, title: 'Write a program to implement kosaraju algorithm.', difficulty: 'Hard', solved: false },
    { id: 19, title: 'Write a program to implement tarjan algorithm.', difficulty: 'Hard', solved: false },
    { id: 20, title: 'Write a program to find biconnected components.', difficulty: 'Hard', solved: false },
    { id: 21, title: 'Write a program to implement graph coloring.', difficulty: 'Hard', solved: false },
    { id: 22, title: 'Write a program to find eulerian path.', difficulty: 'Hard', solved: false },
    { id: 23, title: 'Write a program to find hamiltonian path.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to implement A* search algorithm.', difficulty: 'Hard', solved: false },
    { id: 25, title: 'Write a program to find maximum flow using ford fulkerson.', difficulty: 'Hard', solved: false },
    { id: 26, title: 'Write a program to implement edmonds karp algorithm.', difficulty: 'Hard', solved: false },
    { id: 27, title: 'Write a program to find minimum cut.', difficulty: 'Hard', solved: false },
    { id: 28, title: 'Write a program to implement bipartite matching.', difficulty: 'Hard', solved: false },
    { id: 29, title: 'Write a program to find all pairs shortest path.', difficulty: 'Hard', solved: false },
    { id: 30, title: 'Write a program to implement graph isomorphism.', difficulty: 'Hard', solved: false },
  ],
  'dynamic-programming': [
    { id: 1, title: 'Write a program to implement fibonacci using DP.', difficulty: 'Easy', solved: false },
    { id: 2, title: 'Write a program to find longest common subsequence.', difficulty: 'Medium', solved: false },
    { id: 3, title: 'Write a program to find longest increasing subsequence.', difficulty: 'Medium', solved: false },
    { id: 4, title: 'Write a program to implement 0/1 knapsack.', difficulty: 'Medium', solved: false },
    { id: 5, title: 'Write a program to implement unbounded knapsack.', difficulty: 'Medium', solved: false },
    { id: 6, title: 'Write a program to find edit distance.', difficulty: 'Hard', solved: false },
    { id: 7, title: 'Write a program to find minimum path sum.', difficulty: 'Medium', solved: false },
    { id: 8, title: 'Write a program to find maximum subarray sum.', difficulty: 'Easy', solved: false },
    { id: 9, title: 'Write a program to implement coin change.', difficulty: 'Medium', solved: false },
    { id: 10, title: 'Write a program to find subset sum.', difficulty: 'Medium', solved: false },
    { id: 11, title: 'Write a program to implement rod cutting.', difficulty: 'Medium', solved: false },
    { id: 12, title: 'Write a program to find longest palindromic subsequence.', difficulty: 'Hard', solved: false },
    { id: 13, title: 'Write a program to implement matrix chain multiplication.', difficulty: 'Hard', solved: false },
    { id: 14, title: 'Write a program to find palindrome partitioning.', difficulty: 'Hard', solved: false },
    { id: 15, title: 'Write a program to implement word break.', difficulty: 'Medium', solved: false },
    { id: 16, title: 'Write a program to find maximum profit in stock.', difficulty: 'Medium', solved: false },
    { id: 17, title: 'Write a program to implement egg dropping problem.', difficulty: 'Hard', solved: false },
    { id: 18, title: 'Write a program to find longest common substring.', difficulty: 'Medium', solved: false },
    { id: 19, title: 'Write a program to implement wildcard matching.', difficulty: 'Hard', solved: false },
    { id: 20, title: 'Write a program to find minimum jumps.', difficulty: 'Medium', solved: false },
    { id: 21, title: 'Write a program to implement partition problem.', difficulty: 'Medium', solved: false },
    { id: 22, title: 'Write a program to find box stacking problem.', difficulty: 'Hard', solved: false },
    { id: 23, title: 'Write a program to implement optimal BST.', difficulty: 'Hard', solved: false },
    { id: 24, title: 'Write a program to find maximum sum increasing subsequence.', difficulty: 'Medium', solved: false },
    { id: 25, title: 'Write a program to implement catalan number.', difficulty: 'Medium', solved:  false },
    { id: 26, title: 'Write a program to find minimum cost path.', difficulty: 'Medium', solved: false },
    { id: 27, title: 'Write a program to implement boolean parenthesization.', difficulty: 'Hard', solved: false },
    { id: 28, title: 'Write a program to find shortest common supersequence.', difficulty: 'Hard', solved: false },
    { id: 29, title: 'Write a program to implement counting bits.', difficulty: 'Easy', solved: false },
    { id: 30, title: 'Write a program to find house robber problem.', difficulty: 'Easy', solved: false },
  ],
}